FROM ruby:2.2

ENV TERM xterm
ENV LANG C.UTF-8
ENV http_proxy http://172.28.4.7:8080
ENV https_proxy http://172.28.4.7:8080

RUN git config --global url.https://github.com/.insteadOf git://github.com/

RUN apt-get update -qq
RUN apt-get install -y nodejs

ENV APP_PATH /app

WORKDIR $APP_PATH

ADD Gemfile Gemfile

ADD Gemfile.lock Gemfile.lock

RUN bundle install

ADD . .

RUN ["bundle", "exec", "middleman", "build", "--clean"]
